### ISSUE TITLE
Indonesia Vetiver Network page

### ISSUE THREAD

**Issue by altonwebsites** [altonwebsites/EBPP#10]
If you scroll down, the image is squashed

**Comment by altonwebsites** [comment]
I don't understand this issue

**Comment by altonwebsitesebpp** [comment]
Hi steve, 
If you go to the tab "About us" then "Information" then "Indonesia Vetiver Network" and you scroll down the page, you will see under the title "Examples of Vetiver Growth" and the images there are squashed. 
Let me know if you don't see it for some reason. Is this fixable?
Thanks,
M

**Comment by altonwebsites** [comment]
Hi Michelle, 
Can you take a look now please. I've given the images a bit more space in the table but the original images are very small.

**Comment by altonwebsitesebpp** [comment]
Hi Steve, the images are not loading on the page... 

Are you able to check yours?

Thanks!

**Comment by altonwebsites** [comment]
Fixed, sorry, I had to copy the entire page from my computer to fix the image-spacing. The links on the images were to my "local" version of the site

**Comment by altonwebsitesebpp** [comment]
Sorry still images are appearing squashed.

Under the titles:

Stabilising road verges

Improving Gullies problems

and a few others are tiny..

**Comment by altonwebsites** [comment]
Images fixed
