### ISSUE TITLE
Blog summary page styling

### ISSUE THREAD

**Issue by altonwebsites** [altonwebsites/EBPP#13]
The blog story headlines should be bolded, FONT to change and colour of headlines black, lines between the blog stories to separate the stories bolder/darker like previous site

Clarification from email: Here the larger font is more noticeable and you'll see from our original format that each article stood out with the Bold, Black font, in its own box. Is it easy to revert to style like the original?

**Comment by altonwebsites** [comment]
Note to self: uplod screenshot of original blog entry

**Comment by altonwebsites** [comment]
![screen shot 2015-01-08 at 11 03 34](https://cloud.githubusercontent.com/assets/10417228/5661645/116d5358-9726-11e4-91f7-43da03a257c0.png)

**Comment by altonwebsites** [comment]
Reverted to the original page styling but with the images included on the right. The headlines on the original page were green (as shown in screenshot above) rather than black as requested. I can change these to black if prefered

**Comment by altonwebsitesebpp** [comment]
looks great!
