### ISSUE TITLE
Campaigns

### ISSUE THREAD

**Issue by altonwebsites** [altonwebsites/EBPP#14]
Can we create a sub-tab for “Water & Sanitation” and then a click through to the page, which EBPP needs to populate with content. In the future we may wish to add more sub-categories such as “Education”, “Agriculture” etc. Would this be easy to do?

**Comment by altonwebsites** [comment]
I'm not sure what you're asking here.
 
Is the sub-tab a drop-down menu on the navigation menu bar, or in the page itself? 

1. If it's a drop-down menu it would have to look something like this:

Home
About Us - [ menu item | menu item | menu item ]
Get Involved - [ menu item | menu item | menu item ]
Blog 
Campaigns - [Our Campaigns   |    Water & Sanitation]
Contact
Donate  
                      
                      
 
Where the "Campaigns" text is a trigger to open the drop-down menu rather than a link to a Campaigns page. 

2. If it's in the page itself, what other content does the Campaigns page have?

Might be best to discuss this on Skype.

**Comment by altonwebsitesebpp** [comment]
Hi Steve, just for clarity - we did mean option 1. i.e. a drop down menu on the navigation bar. 
Is it easy for us to create this later on? It's just that at the moment, we only have one campaign which is a toilets fundraising campaign and that would logically sit under the topic of "Water & Sanitation". 
We might have others in the future for other programme areas such as "Environment" or "Education". 

It's not a NECESSITY for this campaign as we only have one at the moment. I was just curious if it would be easy to set up if/when we do have more than one campaign running at a time.  

Does this make sense?

**Comment by altonwebsites** [comment]
See the current Menu bar. The "Our Campaigns" menu item can be removed / renamed easily.
