### ISSUE TITLE
Slideshow

### ISSUE THREAD

**Issue by altonwebsites** [altonwebsites/EBPP#15]
Slideshow – enable more images (perhaps up to 10) to be added and check that images here can be hyperlinked?

**Comment by altonwebsites** [comment]
The slideshow can take as many images as you like but the page load time is likely to decrease - recommend about 4-5. 

Images can be hyperlinked and the slideshow plugin I've added allows animated text & links to be overlaid on the images.

If you send me a couple of photos (or use the existing 2) and tell me what text you'd like to appear over the top and where you want the text / image to link to I can set these up as examples.

**Comment by altonwebsitesebpp** [comment]
This is great Steve! We will have an image to upload for the toilets campaign we will be launching on 26 Jan. Until then we are a bit swamped at the moment so we won't have time to do this right now. Will get back to you or figure out how to update ourselves! 
Thanks!
