### ISSUE TITLE
Donation price point banner 

### ISSUE THREAD

**Issue by altonwebsites** [altonwebsites/EBPP#16]
is it possible for this to change while you are on the page? If we provide another 5 price points?

**Comment by altonwebsites** [comment]
Yes. 
You can add content for the Donations Banner from the Donations Banner menu item on the left hand side of the admin pages

**Comment by altonwebsites** [comment]
Banner content cycling added - add content for the Donations Banner from the Donations Banner menu item on the left hand side of the admin pages. Take care with the word count.
Please confirm acceptance and closure if ok.

**Comment by altonwebsitesebpp** [comment]
Thanks Steve. We will update this as we finalise the list of donation items.
