### ISSUE TITLE
Newsletter mailing list

### ISSUE THREAD

**Issue by altonwebsites** [altonwebsites/EBPP#19]
Newsletter mailing list question: Do you know how to export a mailing list from wordpress that has First Name, Surname and other details? We tried to export a list and it only came out with email

**Comment by altonwebsites** [comment]
Newsletter subscription button enabled on home page

**Comment by altonwebsitesebpp** [comment]
can you please confirm whether we receive first and last name as well as email?

**Comment by altonwebsites** [comment]
See the "Newsletter email address export - pt 2" email from 14th January - the only info the plugin was set up to capture on the original site was the email address, which is why you were unable to export any other data

![pastedgraphic-1](https://cloud.githubusercontent.com/assets/10417228/5772689/51db93d6-9d4e-11e4-8d13-ccbec33e50f9.png)

**Comment by altonwebsitesebpp** [comment]
ok is there a way we can collect first and last names or is it restricted and only available if we upgrade?

**Comment by altonwebsites** [comment]
First & Last names added
