### ISSUE TITLE
Navigation Menu tabs

### ISSUE THREAD

**Issue by altonwebsites** [altonwebsites/EBPP#2]
Different style of tab for “About us” and “Get Involved” 

ACTION: Can we make the tabs consistent and change “About Us” style to “Get Involved” 

About Us: Have sub-tabs like the “Get Involved” tab for the Programmes, News & Media, About Us, then for each of those sub-tabs, when you hover over it, the topics appear across to the right

**Comment by altonwebsites** [comment]
Clarification from email: “We would like to avoid the menu sections headings spreading across the page. Can you just put each of the 4 headings and then, when cursor goes on that, the specific heading gives the side-box sub headings”

**Comment by altonwebsites** [comment]
Completed. Please confirm acceptance.

**Comment by altonwebsitesebpp** [comment]
Great! thanks steve!
