### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by altonwebsites** [altonwebsites/EBPP#22]
Add names and acknoldgements text

吉川絵美 Emi Yoshikawa 
片桐麻衣 Mai Katagiri
佐藤加奈子 Kanako Sato
松田早苗 Sanae Matsuda

**Comment by altonwebsitesebpp** [comment]
David, 
Do you want to write something briefly to cover the acknowledgement that Emi could translate? 

e.g. something like "Many thanks to Emi Yoshikawa, Mai Katagiri, Kanako Sato, Sanae Matsuda for the translation”

The alternative would just be a list of names.

**Comment by altonwebsites** [comment]
David, Do you want to write some covering text to acknowledge the translators that Emi could translate?

e.g. "Many thanks to Emi Yoshikawa, Mai Katagiri, Kanako Sato, Sanae Matsuda for all their hard work on the translation"

The alternative would just be a list of names

**Comment by altonwebsites** [comment]
Added the text provided by Emi at the bottom of the page:

EBPPウェブサイトの日本語版の翻訳は吉川絵美さん、片桐麻衣さん、佐藤加奈子さん、松田早苗さんにご協力頂きました。一同感謝申し上げます。

Please confirm that this can be closed
