### ISSUE TITLE
Enable page translations plugin

### ISSUE THREAD

**Issue by altonwebsites** [altonwebsites/EBPP#23]
Translation plugin enabled. 

The very variable length of the translated text makes the green buttons unusable - translation is turned off for these. An alternative might be to have text rather than buttons if translation is necessary

The plugin is unable to translate the text content of the donations banner because of the way it cycles through it's content. If translation is required I'll need to turn off the cycling. It's still possible to provide random content but only when the page loads.

**Comment by altonwebsitesebpp** [comment]
not necessary. fine as is. We've just gone through each language translation and all looks to fit and is fine.
