### ISSUE TITLE
Improve 404 page

### ISSUE THREAD

**Issue by altonwebsites** [altonwebsites/EBPP#25]
The 404 page is the what the visitor sees when there isn't a page on the site that matches the URL in the address bar.

**Comment by altonwebsites** [comment]
Added text and links for the visitor to contact the site if they believe a link is broken. Can be seen here:

http://www.eastbalipovertyproject.org/broken-link-example

**Comment by altonwebsitesebpp** [comment]
yes it's fine. Thanks. Though can we pls fix the spelling of Capitalisation. 

Thank you!
