### ISSUE TITLE
Donations Banner Changes

### ISSUE THREAD

**Issue by altonwebsites** [altonwebsites/EBPP#28]
I've changed the way that the donations banner is updated. 

I've removed the Donations Banner menu item on the left hand side of the admin page, and added a Donations Banner field to the Home page Edit screen. 

This makes banner editing consistent with other items on the home page edit screen - footer, header menus, mission statement - and prevents the donation banner content from appearing as a type of blog post.

**Comment by altonwebsitesebpp** [comment]
Just for clarification, when you say:I've removed the Donations Banner menu item on the left hand side of the admin page, and added a Donations Banner field to the Home page Edit screen

Are you referring to the back end of wordpress??

**Comment by altonwebsites** [comment]
Sorry, yes that's right
