### ISSUE TITLE
Facebook and the WP Book plugin

### ISSUE THREAD

**Issue by altonwebsites** [altonwebsites/EBPP#31]
Have you been able to cross-post blog entries automatically to Facebook using WP Book, in the last 3years? The EBPP site doesn't have an SSL certificate (https://) required by Facebook for posting directly so I assume that you haven't automatically posted to Facebook using WP Book. Is this correct?

The not-so-interesting reason behind my question: 

I receive the following error message when publishing on certain admin pages: "Both user access token AND page access_token are blank. You must grant permissions before publishing will work." I assumed this was a compatibility issue related to a new plugin but it's related to Facebook / WP Book's permissions. Facebook now (in the last 3 years) requires websites to have an SSL (Secure Socket Layer) certificate installed to post directly to their pages. A WPBook support ticket here https://wordpress.org/support/topic/plugin-wpbook-ssl-required supports this also saying that an SSL certificate is required for WPBook.

**Comment by altonwebsitesebpp** [comment]
First point - No cross post blog entries and no intention to do so at present. 

Ok, so what are the next steps or requirements of EBPP for this SSL certificate? If we have no intention of doing cross post blog entries, is this relevant to us?

Thanks,
D&M

**Comment by altonwebsites** [comment]
If you've no need for cross-posting to Facebook using the plugin, there's no need for the certificate.

**Comment by altonwebsitesebpp** [comment]
Great! Thanks!
