### ISSUE TITLE
Navigation bar and translation

### ISSUE THREAD

**Issue by altonwebsites** [altonwebsites/EBPP#32]
The navigation bar now shows a green space on the right-hand-side of the Donate menu item. The Transposh language translation plugin requires that the menus are flexible (horizontally) to account for changes in text length when the translation is done.

If you prefered the neat fixed-width menu, I need to disable the translation for the navigation and its dropdowns menus. 

If you want the menu translated by the Transposh plugin, the green space is unavoidable.

Sorry, not a very exciting issue. Will try harder next time

**Comment by altonwebsitesebpp** [comment]
ok Steve. Thanks for the clarification. Happy as it is. 

D & M
